"""Empreinte de plateforme : reconnaître comment l'app a été vibe codée.

Utile pour deux raisons :
  1. adapter les détecteurs (une app Lovable = quasi toujours Supabase) ;
  2. enrichir le rapport et la collecte (statistiques par plateforme).

IMPORTANT : la détection de plateforme n'est JAMAIS bloquante. Quel que soit
l'outil ayant généré le code (Lovable, Bolt, v0, Replit, Cursor, Windsurf,
Claude Code, Codex, Copilot… ou aucun), tous les détecteurs s'exécutent de la
même façon. Une plateforme "inconnue" est analysée exactement comme les autres.
"""
from __future__ import annotations
from pathlib import Path

# (plateforme, indices de fichiers, indices de contenu)
_SIGNS = [
    ("Lovable",  ["lovable.config", ".lovable"], ["lovable.dev", "gpt-engineer"]),
    ("Bolt",     ["bolt.config", ".bolt"],       ["bolt.new", "stackblitz"]),
    ("v0",       [],                              ["v0.dev", "generated by v0"]),
    ("Replit",   [".replit", "replit.nix"],       ["replit"]),
    ("Cursor",   [".cursor", ".cursorrules"],      ["cursor"]),
    ("Windsurf", [".windsurf", ".windsurfrules"],  ["windsurf", "codeium"]),
    ("Claude Code", ["CLAUDE.md", ".claude"],       ["claude code", "anthropic"]),
    ("Codex",    ["AGENTS.md", ".codex"],            ["openai codex", "codex-cli"]),
    ("Copilot",  [".github/copilot"],                ["github copilot", "copilot-instructions"]),
]


def detect(root: Path) -> str:
    files = {p.name for p in root.rglob("*") if p.is_file() and p.name.startswith(".")}
    # 1. indice par fichier de config
    for name, file_hints, _ in _SIGNS:
        if any(any(f.startswith(h) for f in files) for h in file_hints):
            return name
    # 2. indice par contenu (README, package.json)
    blob = ""
    for cand in ("README.md", "package.json", "index.html"):
        p = root / cand
        if p.is_file():
            try:
                blob += p.read_text(errors="ignore").lower()
            except OSError:
                pass
    for name, _, content_hints in _SIGNS:
        if any(h in blob for h in content_hints):
            return name
    # 3. stack devinée (aide quand même les détecteurs)
    if (root / "package.json").is_file():
        pkg = (root / "package.json").read_text(errors="ignore").lower()
        if "next" in pkg:
            return "Next.js (générateur inconnu)"
        if "vite" in pkg or "react" in pkg:
            return "React/Vite (générateur inconnu)"
    return "inconnue"


def uses_supabase(ctx) -> bool:
    for p in ctx.iter_files():
        if p.name == "package.json" and "@supabase/supabase-js" in ctx.read(p):
            return True
    return False
